/**
 * Check a generated collection against the chain and against its upload, before the
 * contract is pointed at it or frozen. `scripts/reveal.sh` runs this.
 *
 *   npm run check-reveal -- --network sepolia --uri ipfs://<METADATA_CID>/
 *   npm run check-reveal -- --network sepolia --uri ipfs://<METADATA_CID>/ --final
 *
 * For every token 1..count in output/collection/<network>/collection.json:
 *   - the chain still says it was claimed by the address its card was drawn from
 *     (a reorganisation can reorder claims made close together)
 *   - <uri><id>.json is served, and equals the generated file
 *   - its image is served, and has exactly the generated bytes
 * With --final, also that the contract reveals exactly those tokens from exactly that
 * location, and that nothing else has been minted: what freezing makes permanent.
 *
 * Options:
 *   --gateway <url>  where ipfs:// paths are fetched from (default https://ipfs.io)
 *   --quick          only confirm images exist, except the first and last
 *   --dir <dir>      the collection (default output/collection/<network>)
 *
 * Exit status: 0 when everything checks out; 1 when something is wrong; 2 when nothing
 * is wrong but some files could not be fetched, which is normal for a few minutes
 * after an upload.
 */
import {createHash} from "node:crypto";
import {existsSync, readdirSync, readFileSync} from "node:fs";
import {join, resolve} from "node:path";
import {isDeepStrictEqual} from "node:util";
import {getAddress} from "viem";
import {imageFileName, imageUri, metadataFileName} from "../src/metadata";
import {fromRoot} from "../src/paths";
import {NFT_ABI, connect} from "./chain";
import {parseArgs, stringArg} from "./cli";
import {mapLimit} from "./html";
import {imagesBase, metadataBase} from "./locations";
import {COLLECTION_MANIFEST, type CollectionManifest} from "./manifest";

const TIMEOUT_MS = Number(process.env.FETCH_TIMEOUT ?? 90) * 1000;

const wrong: string[] = [];
const unreachable: string[] = [];

type Fetched = {status: number; body: Buffer | null} | null;

async function get(url: string, method: "GET" | "HEAD" = "GET"): Promise<Fetched> {
  try {
    const response = await fetch(url, {method, signal: AbortSignal.timeout(TIMEOUT_MS)});
    const body = method === "GET" && response.ok ? Buffer.from(await response.arrayBuffer()) : null;
    return {status: response.status, body};
  } catch {
    return null;
  }
}

/** Sort a failed fetch into "the upload lacks this file" or "could not tell". */
function failed(what: string, result: Fetched): void {
  if (result && (result.status === 404 || result.status === 410)) {
    wrong.push(`${what} is not in the upload (HTTP ${result.status})`);
  } else {
    unreachable.push(`${what}: ${result ? `HTTP ${result.status}` : "no response"}`);
  }
}

const sha256 = (data: Buffer): string => createHash("sha256").update(data).digest("hex");

async function main(): Promise<number> {
  const args = parseArgs();
  const network = stringArg(args, "network");
  const uri = stringArg(args, "uri");
  if (!network || !uri) throw new Error("usage: npm run check-reveal -- --network <network> --uri <location> [--final] [--quick]");
  const gateway = stringArg(args, "gateway") ?? process.env.IPFS_GATEWAY ?? "https://ipfs.io";
  const final = args.final === true;
  const quick = args.quick === true;
  const base = metadataBase(uri, gateway);

  const dir = resolve(fromRoot(), stringArg(args, "dir") ?? join("output", "collection", network));
  const manifestPath = join(dir, COLLECTION_MANIFEST);
  if (!existsSync(manifestPath)) throw new Error(`no ${manifestPath}. Run: npm run collection -- --network ${network}`);
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as CollectionManifest;
  const {count, imageCid, tokens} = manifest;

  // The files on disk, before anything is fetched.
  if (!imageCid) {
    throw new Error(`the image CID is not set. Upload images/, then: npm run set-image-cid -- --dir ${dir} --cid <IMAGE_CID>`);
  }
  if (tokens.length !== count) throw new Error(`${COLLECTION_MANIFEST} lists ${tokens.length} tokens but says ${count}`);
  const expectedFiles = Array.from({length: count}, (_, i) => metadataFileName(String(i + 1))).sort();
  const actualFiles = readdirSync(join(dir, "metadata")).filter((f) => f.endsWith(".json")).sort();
  if (!isDeepStrictEqual(actualFiles, expectedFiles)) throw new Error(`${dir}/metadata should hold exactly 1.json..${count}.json`);
  const local = tokens.map((token) => {
    const metadata = JSON.parse(readFileSync(join(dir, "metadata", metadataFileName(token.tokenId)), "utf8"));
    if (metadata.image !== imageUri(imageCid, token.tokenId)) {
      throw new Error(`metadata/${token.tokenId}.json points at ${metadata.image}, not at the uploaded images`);
    }
    return metadata as unknown;
  });

  // The chain.
  const {client, deployment} = await connect(network);
  if (manifest.contract.toLowerCase() !== deployment.contractAddress.toLowerCase() || manifest.chainId !== deployment.chainId) {
    throw new Error(`${manifestPath} is for ${manifest.contract} on chain ${manifest.chainId}, not deployments/${network}.json`);
  }
  const contract = {address: deployment.contractAddress, abi: NFT_ABI} as const;
  const [totalMinted, revealedCount, baseURI] = await Promise.all([
    client.readContract({...contract, functionName: "totalMinted"}),
    client.readContract({...contract, functionName: "revealedCount"}),
    client.readContract({...contract, functionName: "baseURI"})
  ]);
  console.log(`Checking tokens 1..${count} of ${deployment.contractAddress} on ${network}`);
  console.log(`  against ${uri}${base === uri ? "" : ` (fetched from ${base})`}`);

  if (Number(totalMinted) < count) wrong.push(`the contract has minted ${totalMinted} tokens, fewer than the ${count} generated`);
  if (final) {
    if (Number(revealedCount) !== count) wrong.push(`the contract reveals ${revealedCount} tokens, not ${count}`);
    if (Number(totalMinted) !== count) wrong.push(`${totalMinted} tokens are minted but the collection has ${count}`);
    if (baseURI !== uri) wrong.push(`the contract points at ${baseURI || "nothing"}, not ${uri}`);
  }

  const claimers = await mapLimit(tokens, 8, (token) =>
    client.readContract({...contract, functionName: "claimerOf", args: [BigInt(token.tokenId)]})
  );
  let claimersOk = 0;
  claimers.forEach((claimer, i) => {
    if (getAddress(claimer) === getAddress(tokens[i]!.claimer)) claimersOk++;
    else wrong.push(`token ${tokens[i]!.tokenId} was claimed by ${claimer}, but its card was drawn for ${tokens[i]!.claimer}: generate again`);
  });
  console.log(`  claimers   ${claimersOk} of ${count} match the chain`);

  // The upload.
  let metadataOk = 0;
  await mapLimit(tokens, 8, async (token, i) => {
    const name = metadataFileName(token.tokenId);
    const result = await get(`${base}${name}`);
    if (!result?.body) return failed(name, result);
    let served: unknown;
    try {
      served = JSON.parse(result.body.toString("utf8"));
    } catch {
      return void wrong.push(`${name} in the upload is not valid JSON`);
    }
    if (isDeepStrictEqual(served, local[i])) metadataOk++;
    else wrong.push(`${name} in the upload differs from the generated one`);
  });
  console.log(`  metadata   ${metadataOk} of ${count} identical to the generated files`);

  let imagesOk = 0;
  const images = imagesBase(imageCid, gateway);
  await mapLimit(tokens, 4, async (token, i) => {
    const name = imageFileName(token.tokenId);
    const whole = !quick || i === 0 || i === count - 1;
    if (!whole) {
      const head = await get(`${images}${name}`, "HEAD");
      if (head && head.status === 200) return void imagesOk++;
      if (head && head.status !== 405 && head.status !== 501) return failed(`image ${name}`, head);
    }
    const result = await get(`${images}${name}`);
    if (!result?.body) return failed(`image ${name}`, result);
    if (sha256(result.body) === token.imageSha256) imagesOk++;
    else wrong.push(`image ${name} in the upload differs from the generated one`);
  });
  console.log(`  images     ${imagesOk} of ${count} ${quick ? "present (first and last compared byte for byte)" : "identical to the generated files"}`);

  const list = (items: string[]) => {
    for (const item of items.slice(0, 10)) console.log(`    - ${item}`);
    if (items.length > 10) console.log(`    ... and ${items.length - 10} more`);
  };
  if (wrong.length > 0) {
    console.log(`\n${wrong.length} problem(s):`);
    list(wrong);
    return 1;
  }
  if (unreachable.length > 0) {
    console.log(`\n${unreachable.length} file(s) could not be fetched:`);
    list(unreachable);
    return 2;
  }
  console.log("\nEverything matches.");
  return 0;
}

main().then(
  (code) => process.exit(code),
  (error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
);
